//? Save Compoungin Medicine Constants
export const SAVE_COMPOUNDING_MEDICINE_REQUEST =
  'SAVE_COMPOUNDING_MEDICINE_REQUEST'
export const SAVE_COMPOUNDING_MEDICINE_SUCCESS =
  'SAVE_COMPOUNDING_MEDICINE_SUCCESS'
export const SAVE_COMPOUNDING_MEDICINE_FAIL = 'SAVE_COMPOUNDING_MEDICINE_FAIL'
